In [87]:
import pandas as pd

In [88]:
df=pd.read_csv('heart.csv')

In [89]:
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [90]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [91]:
from sklearn.preprocessing import LabelEncoder

In [92]:
encoder=LabelEncoder()

In [93]:
col=('Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope')
for i in col:
    df[i]=encoder.fit_transform(df[i])

In [94]:
df

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    1              1        140          289          0           1   
1     49    0              2        160          180          0           1   
2     37    1              1        130          283          0           2   
3     48    0              0        138          214          0           1   
4     54    1              2        150          195          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    1              3        110          264          0           1   
914   68    1              0        144          193          1           1   
915   57    1              0        130          131          0           1   
916   57    0              1        130          236          0           0   
917   38    1              2        138          175          0           1   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0      172               0      0.0         2             0  
1      156               0      1.0         1             1  
2       98               0      0.0         2             0  
3      108               1      1.5         1             1  
4      122               0      0.0         2             0  
..     ...             ...      ...       ...           ...  
913    132               0      1.2         1             1  
914    141               0      3.4         1             1  
915    115               1      1.2         1             1  
916    174               0      0.0         1             1  
917    173               0      0.0         2             0  

[918 rows x 12 columns]

In [95]:
df.ChestPainType.unique()

array([1, 2, 0, 3])

In [96]:
x=df.drop('HeartDisease',axis=1)

In [97]:
y=df.HeartDisease

In [98]:
#scale the features

In [99]:
from sklearn.preprocessing import StandardScaler

In [100]:
scale=StandardScaler()

In [101]:
scaled=scale.fit_transform(x)

In [102]:
scaled_df=pd.DataFrame(scaled,columns=x.columns)

In [103]:
scaled_df.head()

Age       Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  \
0 -1.433140  0.515952       0.229032   0.410909     0.825070  -0.551341   
1 -0.478484 -1.938163       1.275059   1.491752    -0.171961  -0.551341   
2 -1.751359  0.515952       0.229032  -0.129513     0.770188  -0.551341   
3 -0.584556 -1.938163      -0.816995   0.302825     0.139040  -0.551341   
4  0.051881  0.515952       1.275059   0.951331    -0.034755  -0.551341   

   RestingECG     MaxHR  ExerciseAngina   Oldpeak  ST_Slope  
0    0.017255  1.382928       -0.823556 -0.832432  1.052114  
1    0.017255  0.754157       -0.823556  0.105664 -0.596078  
2    1.601219 -1.525138       -0.823556 -0.832432  1.052114  
3    0.017255 -1.132156        1.214246  0.574711 -0.596078  
4    0.017255 -0.581981       -0.823556 -0.832432  1.052114

In [104]:
from sklearn.model_selection import train_test_split

In [134]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [106]:
from sklearn.svm import SVC

In [107]:
svm=SVC()

In [108]:
svm.fit(x_train,y_train)

SVC()

In [109]:
svm.score(x_train,y_train)

0.7343324250681199

In [110]:
svm.score(x_test,y_test)

0.6847826086956522

In [111]:
svm.predict(x_test)

array([0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1], dtype=int64)

In [112]:
svm.score(x_test,y_test)

0.6847826086956522

In [113]:
# the above is the score using train test and split method
# now lets try the same using cross validation

In [114]:
from sklearn.model_selection import cross_val_score

In [115]:
score=cross_val_score(svm,x,y,cv=10)
score

array([0.61956522, 0.68478261, 0.82608696, 0.83695652, 0.72826087,
       0.67391304, 0.79347826, 0.69565217, 0.62637363, 0.59340659])

In [116]:
score.mean()

0.7078475871954133

In [117]:
# from the above using cross val score we got the same value that we got above using the train test split

In [118]:
# now lets use bagging technique


In [119]:
from sklearn.ensemble import BaggingClassifier

In [120]:
bag=BaggingClassifier(
    estimator=SVC(),
    n_estimators=10,
    max_samples=0.8,
    oob_score=True,
    random_state=None,


)

In [121]:
bag.fit(x_train,y_train)

C:\Users\BHANU PRASAD\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:769: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
C:\Users\BHANU PRASAD\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:775: RuntimeWarning: invalid value encountered in divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]


BaggingClassifier(estimator=SVC(), max_samples=0.8, oob_score=True)

In [122]:

bag.oob_score_

0.723433242506812

In [123]:
bag.score(x_train,y_train)

0.726158038147139

In [124]:
bag.score(x_test,y_test)

0.6739130434782609

In [125]:
score=cross_val_score(bag,x,y,cv=5)

C:\Users\BHANU PRASAD\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:769: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
C:\Users\BHANU PRASAD\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:775: RuntimeWarning: invalid value encountered in divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]
C:\Users\BHANU PRASAD\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:769: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
C:\Users\BHANU PRASAD\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:775: RuntimeWarning: invalid value encountered in divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]
C:\Users\BHANU PRASAD\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:769: UserWarning: Some inputs do 

In [126]:
score

array([0.61413043, 0.81521739, 0.70108696, 0.69398907, 0.6010929 ])

In [127]:
score.mean()

0.6851033499643622

In [128]:
from sklearn.ensemble import RandomForestClassifier

bag=BaggingClassifier(
    estimator=RandomForestClassifier(),
    n_estimators=10,
    max_samples=0.8,
    oob_score=True,
    random_state=None,


)

In [129]:
bag.fit(x_train,y_train)
bag.score(x_train,y_train)

0.9591280653950953

In [130]:
bag.score(x_test,y_test)

0.8858695652173914

In [131]:
rf=RandomForestClassifier()

In [132]:
score=cross_val_score(rf,x,y,cv=5)

In [133]:
score.mean()

0.8169280114041341